SERVER_PORT = '993'
IMAP_SERVER = 'mail.jugoexsim.com'
MAIL_LOGIN = 'reports@jugoexsim.com'
MAIL_PASSWORD = 'QDc70A#b;'
SERVER_PORT1 = '143'
MAIL_LOGIN_DAILY_REPORTS = 'listing.jpps@jugoexsim.com'
MAIL_PASSWORD1 = '#{O$-{#n%97B'

DAILY_PS_TRANSACTION = 'inputfiles/fromps/dailytransactionreports'
PATH_TO_DAILY_REPORT_FILE_PS = 'transformfiles/ps_daily_report'
REPORT_D_PS = 'report_d_ps.csv'
TODAY_TMP_DIR = 'inputfiles/fromps/today_tmp_report_dir'